[package]
name = "snek"
version = "1.0.0"
include = ["src/*.rs", "Cargo.toml"]
publish = false

[dependencies]
winapi = {version = "0.3.9", features = ["winbase", "wincon", "winuser", "handleapi", "processenv", "synchapi"]}
rand = "0.7.3"